### ISSUE TITLE
Error in example files

### ISSUE THREAD

**Issue by tmcclintock** [LSSTDESC/sacc#5]
Having ran the example scripts in the README, an error occurred when running `./examples/split_sacc.py`. Here is the trace:

Traceback (most recent call last):
  File "./examples/split_sacc.py", line 15, in <module>
    save_precision=False, precision_filename="split.precision.sacc")
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/sacc/sacc.py", line 166, in saveToHDF
    t.saveToHDF(tracer_group)
  File "/Users/tmcclintock/anaconda/lib/python2.7/site-packages/sacc/tracer.py", line 57, in saveToHDF
    data=np.zeros(len(self.Nz),dtype=dt)
TypeError: data type not understood

I have Python 2.7, h5py 2.7, and numpy 1.14.3.

**Comment by fjaviersanchez** [comment]
@tmcclintock thanks for checking this. This is related to the update in the definition of numpy dtypes in 1.14. The problem is that the definition of one of the columns had a unicode string in the name and I forced it to string. I made a pull request with the relevant updates and tested it in python/3.6 and 2.7 with numpy 1.13 and 1.14 and it is working (I called it `issues/2` although it should be `issues/5`, sorry about that).
